### PR TITLE
Update the Twig metadata

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by Koc** [comment]
@stof can you also add support of new methods like `getRuntime`? And reflect changes in `getExtension` (now it accepts also class name).

**Comment by stof** [comment]
@Koc I'm not sure what would be provided for ``getRuntime``. Any class name ?

Regarding ``getExtension``, can we provide multiple sources for a provider @Haehnchen ? We would need both the names (existing return provider) and subclass names.

**Comment by Koc** [comment]
> I'm not sure what would be provided for getRuntime. Any class name ?

As I understand - yes. And this method returns the same type of passed class. `$twig->getRuntime('Foo') // returns \Foo`.

**Comment by King2500** [comment]
What happened to `Twig_TemplateInterface`? Is that deprecated/removed from Twig?

**Comment by Koc** [comment]
yes, see http://twig.sensiolabs.org/doc/1.x/deprecated.html#interfaces

**Comment by stof** [comment]
@King2500 using a totally custom implementation of the interface was never well supported (and Twig_Template has always been considered an internal API). This is why the interface was dropped.

**Comment by stof** [comment]
@Haehnchen any news ?

**Comment by King2500** [comment]
I think it's good to merge :+1:

**Pull request merged**
